### ISSUE TITLE
Retrieve Grade Modified Date from Grademark

### ISSUE THREAD

**Issue by mkpelletier** [jmcgettrick/moodle-mod_turnitintooltwo#19]
Hello John,

I was wondering if the API allows for retrieval of the grade modified date from Grademark.  It is available in the grademark screen under the paper information.  It would be very useful for reporting purposes to store that date in the moodle database, like it is in the plagiarism plugin.  Institutional administrators often need to audit turn around time for assignment feedback for quality assurance purposes.

Thanks!

**Comment by jmcgettrick** [comment]
Hi Mathieu,
It doesn't currently but it shouldn't be a problem to include. When you currently read submission data there is a date returned but it's the submission date. I'll investigate it from our end but if you'd like to submit a request through uservoice on the roadmap on the Turnitin website as well that would be great.
I'll leave this issue open until it's released.
Cheers
John

**Comment by jmcgettrick** [comment]
Hi @mkpelletier,
This is in our current roadmap to include but I'm closing this issue as this repository is moving to:https://github.com/turnitin/moodle-mod_turnitintooltwo.
Thanks
John
