### ISSUE TITLE
Version is 2015040107 but version.php keeps saying 2015040106;

### ISSUE THREAD

**Issue by fidelleon** [jmcgettrick/moodle-mod_turnitintooltwo#28]
Moodle plugin interface says there's an update for mod_turnitintwo but, once applied, it keeps telling there's an update available.

Package version says 2015040107 but in version.php:
$plugin->version   = 2015040106;

**Comment by mkpelletier** [comment]
Yes, I had also reported this in response to the release announcement.  Not
sure of it came through.

**Comment by jmcgettrick** [comment]
Apologies, that has now been rectified.
