### ISSUE TITLE
Shared Rubrics

### ISSUE THREAD

**Issue by KenFarr** [jmcgettrick/moodle-mod_turnitintooltwo#40]
Hi

I am trying to set up a Moodle 2.8 integration with Turnitin version 2015040107. All is working well, but we want to use shared rubrics and forms. I have created a form as a top level adminstrator logged directly into Turnitin and shared that form. If I log in as a test tutor, when I go to grade a submitted essay the shared form is available via the rubric section in grademark. However, when I try to create a new turnitin assignment, the "attach a rubric to this assignment" does not list the shared forms, nor are they visible when I launch rubric manager.

What I have found is that once a test user has linked a shared form to an assignment while grading an essay, the shared forms become visable when creating an assignment. 

Am I missing something, or is this a minor bug? 

Ken

**Comment by jmcgettrick** [comment]
Hi @KenFarr - we have recently added shared rubrics to the develop branch but we haven't released the functionality yet as it hasn't been fully put through QA. It required an API change which is now live, so the next release will have the ability to attach shared rubrics to an assignment in it.

**Comment by KenFarr** [comment]
Many thanks, that will be helpful to us. As a work around until the release I can either export the shared forms and send them to users, or tell people how to add a form once a piece of work has been posted. Ken

**Comment by jmcgettrick** [comment]
This is now out with v2015040109
