### ISSUE TITLE
Plugin not emailing receipts unless smtp username and password present

### ISSUE THREAD

**Issue by richheath** [jmcgettrick/moodle-mod_turnitintooltwo#46]
This plugin does not send email receipts unless an smtphost, smtpuser and smtppass are configured in Moodle. In many cases username and password may not be set (in our case we use postfix to send the email to the server, all we have configured is the smtphost).

Please could a different way of testing for messaging be implemented (does this even need doing or does Moodle messaging handle the message output with message_send?). An easy fix would be simply checking for an smtphost, as this is likely the minimum requirement for sending email.

turnitintooltwo_submission.class.php, line 403:

if ( ! empty($CFG->smtphosts) && ! empty($CFG->smtpuser) && ! empty($CFG->smtppass) ) 

could simply be

if ( ! empty($CFG->smtphosts) )

**Comment by jmcgettrick** [comment]
Hi @richheath, we've been made aware of this in https://github.com/jmcgettrick/MoodleDirectV2/issues/453 and will be removing those constraints in our next release which should be quite soon.

**Comment by richheath** [comment]
Great, thanks!

**Comment by jmcgettrick** [comment]
These constraints have now been removed with v2015040109
