### ISSUE TITLE
Error enrolling users after submissions made

### ISSUE THREAD

**Issue by richheath** [jmcgettrick/moodle-mod_turnitintooltwo#48]
We are experiencing an error when enrolling new users on a course (either student or lecturer). It seems to relate to turnitintooltwo assignments on the course that are configured for anonymous marking and have submissions. The users do get enrolled and students are able to submit, but it generates a nasty error in the user picker (See screenshot). This is with Moodle error reporting switched to none and not displaying errors on screen.

![turnitinerror](https://cloud.githubusercontent.com/assets/941746/9988500/00dbf3fe-6049-11e5-979c-a2d4be09af8f.png)

**Comment by jmcgettrick** [comment]
This has been fixed and released in v2015040110. Please note the repository has now moved to the Turnitin account at https://github.com/turnitin/moodle-mod_turnitintooltwo
