### ISSUE TITLE
Uploads not capped to 40mb in Moodle file manager

### ISSUE THREAD

**Issue by richheath** [jmcgettrick/moodle-mod_turnitintooltwo#49]
Uploads are not currently being capped at 40mb (turnitin limit) in the Moodle file manager, but instead taking the course or site limit (in our case 100mb). This means that while the Moodle file manager will accept files > 40mb, when it tries to upload the file to Turnitin's own servers it fails (with no error message, just an empty red box).

**Comment by aspark21** [comment]
That's actually a very good thing for the PP. Not so much for the assignment.

**Comment by jmcgettrick** [comment]
This has been fixed for v2015040110. Please note this repository has now moved to https://github.com/turnitin/moodle-mod_turnitintooltwo
