### ISSUE TITLE
Repository moving accounts.

### ISSUE THREAD

**Issue by jmcgettrick** [jmcgettrick/moodle-mod_turnitintooltwo#56]
Hi, this plugin will be moving from this repository soon. All Moodle plugins will be housed under the Turnitin account at https://github.com/turnitin/.

This plugin's new home will therefore be https://github.com/turnitin/moodle-mod_turnitintooltwo.

Any issues that aren't fixed when this moves will be migrated over to the new repository.

Apologies for the inconvenience.

**Comment by jmcgettrick** [comment]
Tagging people who've contributed previously and those who are watchers or forked this repo.
@drjosephbaxter @sk-unikent @PeloNZ @NeillM @brendanheywood @mattgibson @agrowe @danmarsden @trevor-c @mwehr @jonof @richheath @mkpelletier @KenFarr @aspark21@uofr @lucisgit @SATS-Seminary

**Comment by richheath** [comment]
Great stuff; this will make things much easier!

**Comment by jmcgettrick** [comment]
Closing repo.
Please refer to https://github.com/turnitin/moodle-mod_turnitintooltwo in future.
Thanks
John
